/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPancakeRouteImport } from './routes/api/pancake'
import { Route as ApiPublicMetaCapiRouteImport } from './routes/api/public/meta-capi'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPancakeRoute = ApiPancakeRouteImport.update({
  id: '/api/pancake',
  path: '/api/pancake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCapiRoute = ApiPublicMetaCapiRouteImport.update({
  id: '/api/public/meta-capi',
  path: '/api/public/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/thank-you': typeof ThankYouRoute
  '/api/pancake': typeof ApiPancakeRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/thank-you': typeof ThankYouRoute
  '/api/pancake': typeof ApiPancakeRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/thank-you': typeof ThankYouRoute
  '/api/pancake': typeof ApiPancakeRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/shop'
    | '/thank-you'
    | '/api/pancake'
    | '/api/public/meta-capi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/shop'
    | '/thank-you'
    | '/api/pancake'
    | '/api/public/meta-capi'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/shop'
    | '/thank-you'
    | '/api/pancake'
    | '/api/public/meta-capi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiPancakeRoute: typeof ApiPancakeRoute
  ApiPublicMetaCapiRoute: typeof ApiPublicMetaCapiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pancake': {
      id: '/api/pancake'
      path: '/api/pancake'
      fullPath: '/api/pancake'
      preLoaderRoute: typeof ApiPancakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-capi': {
      id: '/api/public/meta-capi'
      path: '/api/public/meta-capi'
      fullPath: '/api/public/meta-capi'
      preLoaderRoute: typeof ApiPublicMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  ThankYouRoute: ThankYouRoute,
  ApiPancakeRoute: ApiPancakeRoute,
  ApiPublicMetaCapiRoute: ApiPublicMetaCapiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
